services:
    db:
        image: mysql:latest
        container_name: mysql_db
        restart: ${restart}
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            # Configuración del almacenamiento persistente
            - '/path/to/host/uptime/:/app/data'
        command: [
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci'
        ]
    
    api:
        image: ${DOCKER_REGISTRY-}api
        container_name: multimedia_api
        restart: ${restart}
        depends_on:
            - db
        build:
            context: .
            dockerfile: API/Dockerfile
        environment:
            # ASP NET CORE
            - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
        ports:
            - "8080"
            - "8081"
        volumes:
            # Configuración del almacenamiento persistente
            - '/path/to/host/uptime/:/app/data'
            # Microsoft
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            # ASP NET
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    web:
        image: ${DOCKER_REGISTRY-}web
        container_name: multimedia_web
        restart: ${restart}
        depends_on:
            - api
        build:
            context: .
            dockerfile: Web/Dockerfile
        environment:
            # ASP NET CORE
            - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            # Others
            - WebsiteName=Multimedia
        ports:
            - "8080"
            - "8081"
        volumes:
            # Configuración del almacenamiento persistente
            - '/path/to/host/uptime/:/app/data'
            # Microsoft
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            # ASP NET
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
    mysql_data:
        driver: local